name: Site Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-nextjs-static-site:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo  # for Makefile
        uses: actions/checkout@v4

      - name: Install Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Build static site with Next.js
        run: make build
