name: Tag + Release

on:
  push:
    branches:
      - main

jobs:
  tag-and-release:
    uses: topshelfsoftware/.github/.github/workflows/repo-tag-and-release.yaml@main

  deploy-dispatch:
    needs: tag-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch trpubins/portfolio-deploy
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.PORTFOLIO_DEPLOY_PAT }}" \
          https://api.github.com/repos/trpubins/portfolio-deploy/dispatches \
          -d '{"event_type":"triggered_by_repo_portfolio"}'
