name: Tag + Release

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    uses: topshelfsoftware/.github/.github/workflows/repo-auto-tag.yaml@main
  
  auto-release:
    needs: auto-tag
    
    uses: topshelfsoftware/.github/.github/workflows/repo-create-release.yaml@main

  deploy-dispatch:
    needs: auto-tag
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch trpubins/portfolio-deploy
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.PORTFOLIO_DEPLOY_PAT }}" \
          https://api.github.com/repos/trpubins/portfolio-deploy/dispatches \
          -d '{"event_type":"triggered_by_trpubins/portfolio"}'
